apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 6.30.1
    helm:
      valueFiles:
      - $values/loki-app/values.yaml
  - repoURL: 'https://github.com/likhith-tally/argocd-test.git'
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/replicas
